---
name: hello-world-windows-deployment
director_uuid: da12b3a5-a060-427c-a60c-9fd0c7643a3c

releases:
- name: hello-world-windows
  version: latest

networks:
- name: default
  subnets:
  - range: 10.87.23.0/24
    gateway: 10.87.23.1
    reserved: [10.87.23.1, 10.87.23.2]
    dns: [10.87.23.1]
    static: [10.87.23.3, 10.87.23.4, 10.87.23.5]
    cloud_properties:
      name: "stonetalon"

resource_pools:
- name: default
  stemcell:
    name: bosh-vsphere-esxi-windows-2012R2-go_agent
    version: latest
  network: default
  cloud_properties:
    cpu: 2
    ram: 2_048
    disk: 2_048

compilation:
  workers: 1
  network: default
  resource_pool: default
  cloud_properties:
    cpu: 1
    ram: 2_048
    disk: 2_048

update:
  canaries: 0
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: ping-1
  templates:
  - name: call-me-maybe
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [10.87.23.3]
  properties:
    call-me-maybe:
      remote-address: 'http://10.87.23.4:8080/ping'
      server-address: ':8080'
- name: ping-2
  templates:
  - name: call-me-maybe
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [10.87.23.4]
  properties:
    call-me-maybe:
      remote-address: 'http://10.87.23.3:8080/ping'
      server-address: ':8080'
- name: ping-3
  templates:
  - name: call-me-maybe
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [10.87.23.5]
  properties:
    call-me-maybe:
      remote-address: 'http://10.87.23.4:8080/ping'
      server-address: ':8080'
