---
name: hello-world-windows-deployment
director_uuid: f885319a-d429-4995-9210-364a4ccb934d

releases:
- name: hello-world-windows
  version: latest

networks:
- name: default
  subnets:
  - range: 10.87.23.0/24
    gateway: 10.87.23.1
    reserved: [10.87.23.1]
    dns: [10.87.23.1]
    cloud_properties:
      name: "stonetalon"

resource_pools:
- name: default
  stemcell:
    name: bosh-vsphere-esxi-windows-2012R2-go_agent
    version: latest
  network: default
  cloud_properties:
    cpu: 2
    ram: 2_048
    disk: 2_048

compilation:
  workers: 2
  network: default
  resource_pool: default
  cloud_properties:
    cpu: 2
    ram: 2_048
    disk: 2_048

update:
  canaries: 0
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: say-hello
  templates:
  - name: say-hello
  instances: 1
  resource_pool: default
  networks:
  - name: default

- name: errand
  lifecycle: errand
  templates:
  - name: say-hello
  instances: 1
  resource_pool: default
  networks:
  - name: default
