---
name: turbulence-windows
director_uuid: c8a0cccd-6acc-42ed-a98d-d5b83f0bbcd7

releases:
- name: turbulence
  version: latest
- name: sample-windows-release
  version: latest
- name: hello-world-linux
  version: latest

stemcells:
- alias: windows
  os: windows2012R2
  version: latest
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: agent-windows
  instances: 1
  azs: [z1]
  jobs:
  - name: say-hello
    release: sample-windows-release
  - name: turbulence_agent_windows
    release: turbulence
    consumes:
      api: {from: api, deployment: turbulence}
  vm_type: xlarge
  stemcell: windows
  networks:
  - name: windows
    static_ips: [10.10.101.74]
- name: agent-linux
  instances: 1
  azs: [z1]
  jobs:
  - name: say-hello
    release: hello-world-linux
  - name: turbulence_agent
    release: turbulence
    consumes:
      api: {from: api, deployment: turbulence}
  vm_type: default
  stemcell: default
  networks:
  - name: windows
    static_ips: [10.10.101.75]

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-20000
  update_watch_time: 5000-20000
