---
name: call-me-maybe
director_uuid: 8b3d34c7-6262-4c1e-97df-c02105090d2f

releases:
- name: hello-world-windows
  version: latest

networks:
- name: default
  subnets:
  - range: 172.16.1.0/24
    gateway: 172.16.1.1
    reserved: [172.16.1.1]
    dns: [172.16.1.1]
    static: [172.16.1.2, 172.16.1.3, 172.16.1.4]
    cloud_properties:
      name: "VM Network"

resource_pools:
- name: default
  stemcell:
    name: bosh-vsphere-esxi-windows-2012R2-go_agent
    version: latest
  network: default
  cloud_properties:
    cpu: 2
    ram: 2_048
    disk: 2_048

compilation:
  workers: 1
  network: default
  resource_pool: default
  cloud_properties:
    cpu: 2
    ram: 2_048
    disk: 2_048

update:
  canaries: 0
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: ping-1
  templates:
  - name: call-me-maybe
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [172.16.1.2]
  properties:
    call-me-maybe:
      remote-address: 'http://172.16.1.3:8080/ping'
      server-address: ':8080'
- name: ping-2
  templates:
  - name: call-me-maybe
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [172.16.1.3]
  properties:
    call-me-maybe:
      remote-address: 'http://172.16.1.2:8080/ping'
      server-address: ':8080'
- name: ping-3
  templates:
  - name: call-me-maybe
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [172.16.1.4]
  properties:
    call-me-maybe:
      remote-address: 'http://172.16.1.3:8080/ping'
      server-address: ':8080'
