---
name: turbulence-agent
director_uuid: add4217e-d019-4f2b-a6b9-9c203d6fd57d

releases:
- name: turbulence
  version: latest
- name: sample-windows-release
  version: latest
- name: hello-world-linux
  version: latest

stemcells:
- alias: windows
  os: windows2012R2
  version: latest
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: agent-windows
  instances: 1
  azs: [z1]
  jobs:
  - name: say-hello
    release: sample-windows-release
  - name: turbulence_agent_windows
    release: turbulence
    consumes:
      api: {from: api, deployment: turbulence}
  vm_type: large
  stemcell: windows
  networks:
  - name: default
    static_ips: [172.16.1.15]
- name: agent-linux
  instances: 1
  azs: [z1]
  jobs:
  - name: say-hello
    release: hello-world-linux
  - name: turbulence_agent
    release: turbulence
    consumes:
      api: {from: api, deployment: turbulence}
  vm_type: large
  stemcell: default
  networks:
  - name: default
    static_ips: [172.16.1.16]

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-20000
  update_watch_time: 5000-20000
