---
releases:
- name: os-conf
  version: 6
- name: simple-addon-release
  version: 0+dev.5
addons:
- name: misc
  include:
    stemcell: [{os: ubuntu-trusty}]
  jobs:
  - name: login_banner
    release: os-conf
  properties:
    login_banner:
      text: |
        This computer system is for authorized use only. All activity is logged and
        regularly checked by system administrators. Individuals attempting to connect to,
        port-scan, deface, hack, or otherwise interfere with any services on this system
        will be reported.

        BLAH BLAH BLAH
- name: simple-addon-release
  version: 0+dev.5
- name: addon-test
  include:
    stemcell: [{os: windows2012R2}]
  jobs:
  - name: simple-addon
    release: simple-addon-release
